# Generated by Django 6.0.3 on 2026-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=250, null=True, verbose_name='Шлях')),
                ('app_name', models.CharField(max_length=100, verbose_name='Назва файлу')),
                ('key_word', models.CharField(max_length=100, verbose_name='Ключове слово')),
            ],
        ),
        migrations.CreateModel(
            name='Voice_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=100, verbose_name='Ключове слово')),
                ('response', models.TextField(verbose_name='Що відповісти')),
            ],
        ),
    ]
